---
name: auditor
---
Injector:
  AuditLogger:
    class: 'AuditLogger'
    factory: 'SilverStripe\Auditor\AuditFactory'
  ManyManyList:
    class: 'SilverStripe\Auditor\AuditHookManyManyList'
    type: prototype
  Member_GroupSet:
    class: 'SilverStripe\Auditor\AuditHookMemberGroupSet'
    type: prototype
MemberLoginForm:
  extensions:
    - 'SilverStripe\Auditor\AuditHook'
Controller:
  extensions:
    - 'SilverStripe\Auditor\AuditHook'
Member:
  extensions:
    - 'SilverStripe\Auditor\AuditHook'
SiteTree:
  extensions:
    - 'SilverStripe\Auditor\AuditHook'
